"""second part

Revision ID: a7c5fa6d43db
Revises: 6bbb67b72ad8
Create Date: 2025-06-19 22:10:33.393182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a7c5fa6d43db'
down_revision: Union[str, None] = '6bbb67b72ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'environments',
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('param_environment_meaning', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'fatigue_tests',
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'hardness_types',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'load_modes',
        sa.Column('param1_meaning', sa.String(), nullable=False),
        sa.Column('param2_meaning', sa.String(), nullable=True),
        sa.Column('param3_meaning', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'load_signals',
        sa.Column('param1_meaning', sa.String(), nullable=False),
        sa.Column('param2_meaning', sa.String(), nullable=True),
        sa.Column('param3_meaning', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'mediums',
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('param_medium_meaning', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'shapes',
        sa.Column('shape_type', sa.String(), nullable=False),
        sa.Column('dimension1_meaning', sa.String(), nullable=False),
        sa.Column('dimension2_meaning', sa.String(), nullable=True),
        sa.Column('dimension3_meaning', sa.String(), nullable=True),
        sa.Column('dimension4_meaning', sa.String(), nullable=True),
        sa.Column('drawing_file', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'specimen_locations',
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'specimen_orientations',
        sa.Column('orientation', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'specimen_types',
        sa.Column('param1_meaning', sa.String(), nullable=False),
        sa.Column('param2_meaning', sa.String(), nullable=True),
        sa.Column('param3_meaning', sa.String(), nullable=True),
        sa.Column('param4_meaning', sa.String(), nullable=True),
        sa.Column('param5_meaning', sa.String(), nullable=True),
        sa.Column('param6_meaning', sa.String(), nullable=True),
        sa.Column('param7_meaning', sa.String(), nullable=True),
        sa.Column('param8_meaning', sa.String(), nullable=True),
        sa.Column('param9_meaning', sa.String(), nullable=True),
        sa.Column('param10_meaning', sa.String(), nullable=True),
        sa.Column('param11_meaning', sa.String(), nullable=True),
        sa.Column('param12_meaning', sa.String(), nullable=True),
        sa.Column('drawing_file', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'surface_roughness_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'treatment_processes',
        sa.Column('treatment_process_type', sa.String(), nullable=False),
        sa.Column('param1_meaning', sa.String(), nullable=True),
        sa.Column('param2_meaning', sa.String(), nullable=True),
        sa.Column('param3_meaning', sa.String(), nullable=True),
        sa.Column('param4_meaning', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'loads',
        sa.Column('order_number', sa.Integer(), nullable=False),
        sa.Column('repetitions_count', sa.Integer(), nullable=False),
        sa.Column('failure', sa.Boolean(), nullable=False),
        sa.Column('param1_signal', sa.Float(), nullable=False),
        sa.Column('param2_signal', sa.Float(), nullable=True),
        sa.Column('param3_signal', sa.Float(), nullable=True),
        sa.Column('param1_mode', sa.Float(), nullable=True),
        sa.Column('param2_mode', sa.Float(), nullable=True),
        sa.Column('param3_mode', sa.Float(), nullable=True),
        sa.Column('fatigue_test_id', sa.Integer(), nullable=False),
        sa.Column('load_mode_id', sa.Integer(), nullable=False),
        sa.Column('load_signal_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['fatigue_test_id'], ['fatigue_tests.id'], ),
        sa.ForeignKeyConstraint(['load_mode_id'], ['load_modes.id'], ),
        sa.ForeignKeyConstraint(['load_signal_id'], ['load_signals.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'specimens',
        sa.Column('position', sa.String(), nullable=False),
        sa.Column('param1', sa.Float(), nullable=False),
        sa.Column('param2', sa.Float(), nullable=True),
        sa.Column('param3', sa.Float(), nullable=True),
        sa.Column('param4', sa.Float(), nullable=True),
        sa.Column('param5', sa.Float(), nullable=True),
        sa.Column('param6', sa.Float(), nullable=True),
        sa.Column('param7', sa.Float(), nullable=True),
        sa.Column('param8', sa.Float(), nullable=True),
        sa.Column('param9', sa.Float(), nullable=True),
        sa.Column('param10', sa.Float(), nullable=True),
        sa.Column('param11', sa.Float(), nullable=True),
        sa.Column('param12', sa.Float(), nullable=True),
        sa.Column('layout_file', sa.String(), nullable=True),
        sa.Column('drawing_file', sa.String(), nullable=True),
        sa.Column('specimen_type_id', sa.Integer(), nullable=False),
        sa.Column('specimen_orientation_id', sa.Integer(), nullable=False),
        sa.Column('specimen_location_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['specimen_location_id'], ['specimen_locations.id'], ),
        sa.ForeignKeyConstraint(['specimen_orientation_id'], ['specimen_orientations.id'], ),
        sa.ForeignKeyConstraint(['specimen_type_id'], ['specimen_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'specimen_instances',
        sa.Column('instance_number', sa.Integer(), nullable=False),
        sa.Column('specimen_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['specimen_id'], ['specimens.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'stress_concentration_factors',
        sa.Column('scf', sa.String(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('origin', sa.String(), nullable=True),
        sa.Column('specimen_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['specimen_id'], ['specimens.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'surface_roughness',
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('specimen_id', sa.Integer(), nullable=False),
        sa.Column('surface_roughness_type_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['specimen_id'], ['specimens.id'], ),
        sa.ForeignKeyConstraint(['surface_roughness_type_id'], ['surface_roughness_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'semi_products',
        sa.Column('dimension1', sa.Float(), nullable=False),
        sa.Column('dimension2', sa.Float(), nullable=True),
        sa.Column('dimension3', sa.Float(), nullable=True),
        sa.Column('dimension4', sa.Float(), nullable=True),
        sa.Column('material_description_id', sa.Integer(), nullable=False),
        sa.Column('shape_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['material_description_id'], ['material_descriptions.id'], ),
        sa.ForeignKeyConstraint(['shape_id'], ['shapes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'specimen_fatigue_tests',
        sa.Column('stress_level', sa.Float(), nullable=False),
        sa.Column('number_of_cycles_at_end_of_test', sa.Integer(), nullable=False),
        sa.Column('number_of_cycles_at_break', sa.Integer(), nullable=False),
        sa.Column('is_run_out', sa.Boolean(), nullable=False),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('commentary', sa.String(), nullable=True),
        sa.Column('visuals', sa.String(), nullable=True),
        sa.Column('specimen_instance_id', sa.Integer(), nullable=False),
        sa.Column('fatigue_test_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['fatigue_test_id'], ['fatigue_tests.id'], ),
        sa.ForeignKeyConstraint(['specimen_instance_id'], ['specimen_instances.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'hardness',
        sa.Column('position', sa.String(), nullable=True),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('semi_product_id', sa.Integer(), nullable=False),
        sa.Column('hardness_type_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['hardness_type_id'], ['hardness_types.id'], ),
        sa.ForeignKeyConstraint(['semi_product_id'], ['semi_products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'treatments',
        sa.Column('order_number', sa.Integer(), nullable=False),
        sa.Column('param1', sa.Float(), nullable=True),
        sa.Column('param2', sa.Float(), nullable=True),
        sa.Column('param3', sa.Float(), nullable=True),
        sa.Column('param4', sa.Float(), nullable=True),
        sa.Column('param_environment', sa.Float(), nullable=True),
        sa.Column('param_medium', sa.Float(), nullable=True),
        sa.Column('semi_product_id', sa.Integer(), nullable=False),
        sa.Column('treatment_process_id', sa.Integer(), nullable=False),
        sa.Column('environment_id', sa.Integer(), nullable=False),
        sa.Column('medium_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
        sa.ForeignKeyConstraint(['medium_id'], ['mediums.id'], ),
        sa.ForeignKeyConstraint(['semi_product_id'], ['semi_products.id'], ),
        sa.ForeignKeyConstraint(['treatment_process_id'], ['treatment_processes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('chemical_compositions', 'material_description_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chemical_compositions', 'material_description_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_table('treatments')
    op.drop_table('hardness')
    op.drop_table('specimen_fatigue_tests')
    op.drop_table('semi_products')
    op.drop_table('surface_roughness')
    op.drop_table('stress_concentration_factors')
    op.drop_table('specimen_instances')
    op.drop_table('specimens')
    op.drop_table('loads')
    op.drop_table('treatment_processes')
    op.drop_table('surface_roughness_types')
    op.drop_table('specimen_types')
    op.drop_table('specimen_orientations')
    op.drop_table('specimen_locations')
    op.drop_table('shapes')
    op.drop_table('mediums')
    op.drop_table('load_signals')
    op.drop_table('load_modes')
    op.drop_table('hardness_types')
    op.drop_table('fatigue_tests')
    op.drop_table('environments')
    # ### end Alembic commands ###
